included:
  - blocko
excluded:
  - blocko/Supporting Files/R.generated.swift
  - Pods
  - Templates
disabled_rules:
  - nesting
  - object_literal
  - identifier_name
  - type_name
  - force_unwrapping
  - implicitly_unwrapped_optional
  - conditional_returns_on_newline
  - trailing_closure
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  # - force_unwrapping
  # - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_imports
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  
indentation: tabs
cyclomatic_complexity:
  warning: 10
  error: 35
file_length:
  warning: 1000
  error: 10000
function_body_length:
  warning: 50
type_body_length:
  warning: 200
identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - ui
    - cg
    - id
large_tuple:
  warning: 3
  error: 5
line_length:
  warning: 400
  error: 1000
  ignores_function_declarations: true
  ignores_comments: true
